// Claims reais recebidas no JWT do back-end.
// Mantemos estes valores centralizados para evitar strings soltas pelo projecto.
export const CLAIMS = {
  COVERAGE_PERIODS: {
    READ: "read.coverage.periods",
    CREATE: "create.coverage.periods",
    UPDATE: "update.coverage.periods",
    DELETE: "delete.coverage.periods",
    START: "start.coverage.periods",
    CLOSE: "close.coverage.periods",
  },
  COVERAGE_PERIOD_BUDGETS: {
    READ: "read.coverage.period.budgets",
    CREATE: "create.coverage.period.budgets",
    UPDATE: "update.coverage.period.budgets",
    DELETE: "delete.coverage.period.budgets",
  },
  COVERAGE_PERIOD_EXTENSIONS: {
    READ: "read.coverage.period.extensions",
    CREATE: "create.coverage.period.extensions",
    UPDATE: "update.coverage.period.extensions",
  },
  COVERAGE_PERIOD_BUDGET_TRANSACTIONS: {
    READ: "read.coverage.period.budget.transactions",
  },
  ROLES: {
    READ: "read.roles",
    CREATE: "create.roles",
    UPDATE: "update.roles",
    DELETE: "delete.roles",
  },
  ROLE_PERMISSIONS: {
    READ: "read.role.permissions",
    CREATE: "create.role.permissions",
    DELETE: "delete.role.permissions",
  },
  USER_ROLES: {
    READ: "read.user.roles",
    CREATE: "create.user.roles",
    DELETE: "delete.user.roles",
  },
  USERS: {
    READ: "read.users",
    CREATE: "create.users",
    UPDATE: "update.users",
    DELETE: "delete.users",
    ENABLE: "enable.users",
    UNLOCK: "unlock.users",
    CHANGE_PASSWORDS: "change.user.passwords",
    READ_SETTINGS: "read.user.settings",
    UPDATE_SETTINGS: "update.user.settings",
  },
  PERMISSIONS: {
    READ: "read.permissions",
  },
  MODULES: {
    READ: "read.modules",
  },
  SERVICE_PROVIDERS: {
    READ: "read.service.providers",
    CREATE: "create.service.providers",
    UPDATE: "update.service.providers",
    DELETE: "delete.service.providers",
  },
  SERVICE_PROVIDER_ATTACHMENTS: {
    READ: "read.service.provider.attachments",
    CREATE: "create.service.provider.attachments",
    DELETE: "delete.service.provider.attachments",
  },
  SERVICE_PROVIDER_CONTRACT_EXTENSIONS: {
    READ: "read.service.provider.contract.extensions",
    CREATE: "create.service.provider.contract.extensions",
    UPDATE: "update.service.provider.contract.extensions",
  },
  CONTRACT_SERVICE_PROVIDERS: {
    READ: "read.contract.service.providers",
    CREATE: "create.contract.service.providers",
    DELETE: "delete.contract.service.providers",
  },
  ORGANIZATIONS: {
    READ: "read.organizations",
    CREATE: "create.organizations",
    UPDATE: "update.organizations",
    DELETE: "delete.organizations",
  },
  CONTRACTS: {
    READ: "read.contracts",
    CREATE: "create.contracts",
    UPDATE: "update.contracts",
    DELETE: "delete.contracts",
  },
  CONTRACT_ATTACHMENTS: {
    READ: "read.contract.attachments",
    CREATE: "create.contract.attachments",
    DELETE: "delete.contract.attachments",
  },
  CONTRACT_DEPARTMENTS: {
    READ: "read.contract.departments",
    CREATE: "create.contract.departments",
    UPDATE: "update.contract.departments",
    DELETE: "delete.contract.departments",
  },
  CONTRACT_DEPARTMENT_POSITIONS: {
    READ: "read.contract.department.positions",
    CREATE: "create.contract.department.positions",
    UPDATE: "update.contract.department.positions",
    DELETE: "delete.contract.department.positions",
  },
  CONTRACT_HEALTH_PLANS: {
    READ: "read.contract.health.plans",
    CREATE: "create.contract.health.plans",
    UPDATE: "update.contract.health.plans",
    DELETE: "delete.contract.health.plans",
    CLONE: "clone.contract.health.plans",
  },
  CONTRACT_ALLOWED_HOSPITAL_PROCEDURES: {
    READ: "read.contract.allowed.hospital.procedures",
    CREATE: "create.contract.allowed.hospital.procedures",
    UPDATE: "update.contract.allowed.hospital.procedures",
    DELETE: "delete.contract.allowed.hospital.procedures",
  },
  CONTRACT_PERSONS_OF_CONTACT: {
    READ: "read.contract.persons.of.contact",
    CREATE: "create.contract.persons.of.contact",
    UPDATE: "update.contract.persons.of.contact",
    DELETE: "delete.contract.persons.of.contact",
  },
  EMPLOYEE: {
    READ: "read.employees",
    CREATE: "create.employees",
    UPDATE: "update.employees",
    DELETE: "delete.employees",
    TERMINATE: "terminate.employees",
    REHIRE: "rehire.employees",
    UPDATE_BASE_SALARY: "update.employee.base.salary",
  },
  EMPLOYEE_DEPENDENTS: {
    READ: "read.employee.dependents",
    CREATE: "create.employee.dependents",
    UPDATE: "update.employee.dependents",
    DELETE: "delete.employee.dependents",
  },
  EMPLOYEE_DEPENDENT_ATTACHMENTS: {
    READ: "read.employee.dependent.attachments",
    CREATE: "create.employee.dependent.attachments",
    DELETE: "delete.employee.dependent.attachments",
  },
  EMPLOYEE_REHIRES: {
    READ: "read.employee.rehires",
  },
  EMPLOYEE_HEALTH_PLANS: {
    READ: "read.employee.health.plans",
  },
  EMPLOYEE_HOSPITAL_PROCEDURE_PLAN_LIMITS: {
    READ: "read.employee.hospital.procedure.plan.limits",
  },
  EMPLOYEE_HEALTH_PLAN_ADVICE: {
    READ: "read.employee.health.plan.advice",
  },
  INVOICES: {
    READ: "read.invoices",
    CREATE: "create.invoices",
    UPDATE: "update.invoices",
    CANCEL: "cancel.invoices",
    POST: "post.invoices",
    POST_FLAGGED: "post.flagged.invoices",
    REVERSE: "reverse.invoices",
  },
  INVOICE_ITEMS: {
    READ: "read.invoice.items",
    CREATE: "create.invoice.items",
    UPDATE: "update.invoice.items",
    DELETE: "delete.invoice.items",
  },
  INVOICE_FILES: {
    ATTACH: "attach.invoice.files",
    DELETE: "delete.invoice.files",
  },
  CODE_CONFIG: {
    READ: "read.code.config",
    CREATE: "create.code.config",
    UPDATE: "update.code.config",
    DELETE: "delete.code.config",
  },
  SCHEDULED_JOBS: {
    READ: "read.scheduled.jobs",
    CREATE: "create.scheduled.jobs",
    UPDATE: "update.scheduled.jobs",
    DELETE: "delete.scheduled.jobs",
    EXECUTE: "execute.scheduled.jobs",
  },
  SCHEDULED_PARAMETERS: {
    READ: "read.scheduled.parameters",
    CREATE: "create.scheduled.parameters",
    UPDATE: "update.scheduled.parameters",
    DELETE: "delete.scheduled.parameters",
  },
  COUNTRIES: {
    READ: "read.countries",
    CREATE: "create.countries",
    UPDATE: "update.countries",
    DELETE: "delete.countries",
  },
  PROVINCES: {
    READ: "read.provinces",
    CREATE: "create.provinces",
    UPDATE: "update.provinces",
    DELETE: "delete.provinces",
  },
  CURRENCIES: {
    READ: "read.currencies",
    CREATE: "create.currencies",
    UPDATE: "update.currencies",
    DELETE: "delete.currencies",
  },
  LANGUAGES: {
    READ: "read.languages",
    CREATE: "create.languages",
    UPDATE: "update.languages",
    DELETE: "delete.languages",
  },
  INSTITUTION_TYPES: {
    READ: "read.institution.types",
    CREATE: "create.institution.types",
    UPDATE: "update.institution.types",
    DELETE: "delete.institution.types",
  },
  LEAVE_REASONS: {
    READ: "read.leave.reasons",
    CREATE: "create.leave.reasons",
    UPDATE: "update.leave.reasons",
    DELETE: "delete.leave.reasons",
  },
  REASONS: {
    READ: "read.reasons",
    CREATE: "create.reasons",
    UPDATE: "update.reasons",
    DELETE: "delete.reasons",
  },
  PROVIDER_TYPES: {
    READ: "read.provider.types",
    CREATE: "create.provider.types",
    UPDATE: "update.provider.types",
    DELETE: "delete.provider.types",
  },
  TAX_RATES: {
    READ: "read.tax.rates",
    CREATE: "create.tax.rates",
    UPDATE: "update.tax.rates",
    DELETE: "delete.tax.rates",
  },
  HOSPITAL_PROCEDURE_TYPES: {
    READ: "read.hospital.procedure.types",
    CREATE: "create.hospital.procedure.types",
    UPDATE: "update.hospital.procedure.types",
    DELETE: "delete.hospital.procedure.types",
  },
  HOSPITAL_PROCEDURE_CATEGORIES: {
    READ: "read.hospital.procedure.categories",
    CREATE: "create.hospital.procedure.categories",
    UPDATE: "update.hospital.procedure.categories",
    DELETE: "delete.hospital.procedure.categories",
  },
  HOSPITAL_PROCEDURE_CATEGORY_TYPES: {
    READ: "read.hospital.procedure.category.types",
    CREATE: "create.hospital.procedure.category.types",
    DELETE: "delete.hospital.procedure.category.types",
  },
  HOSPITAL_PROCEDURE_GROUPS: {
    READ: "read.hospital.procedure.groups",
    CREATE: "create.hospital.procedure.groups",
    UPDATE: "update.hospital.procedure.groups",
    DELETE: "delete.hospital.procedure.groups",
  },
  HOSPITAL_PROCEDURE_GROUPING: {
    READ: "read.hospital.procedure.grouping",
    CREATE: "create.hospital.procedure.grouping",
    DELETE: "delete.hospital.procedure.grouping",
  },
  REPORTS: {
    READ: "read.reports",
    READ_TREND_LIMITS: "read.trend.limits.reports",
    READ_SERVICE_PROVIDER: "read.service.provider.reports",
    READ_INVOICE_REFERENCE: "read.invoice.reference.reports",
    READ_EMPLOYEE_EXPENSES: "read.employee.expenses.reports",
    READ_COST_PER_EMPLOYEE: "read.cost.per.employee.reports",
    READ_CONTRACT_HOSPITAL_PROCEDURES_BALANCES: "read.contract.hospital.procedures.balances.reports",
    READ_CONTRACT_EMPLOYEE_LIMITS: "read.contract.employee.limits.reports",
    NOTIFY_EMPLOYEE_EXTRACT: "notify.reports.employee.extract.notification",
  },
  DASHBOARDS: {
    READ: "read.dashboards",
  },
  AUDIT_LOGS: {
    READ_SYSTEM: "read.system.audit.logs",
    READ_AUTH: "read.auth.audit.logs",
  },
} as const;

// Lista plana para testes, debug ou comparação com o payload do JWT.
export const ALL_CLAIMS = [
  "read.scheduled.parameters",
  "create.scheduled.parameters",
  "update.scheduled.parameters",
  "delete.scheduled.parameters",
  "read.scheduled.jobs",
  "create.scheduled.jobs",
  "update.scheduled.jobs",
  "delete.scheduled.jobs",
  "execute.scheduled.jobs",
  "read.employees",
  "create.employees",
  "update.employees",
  "delete.employees",
  "terminate.employees",
  "rehire.employees",
  "read.employee.dependents",
  "create.employee.dependents",
  "update.employee.dependents",
  "delete.employee.dependents",
  "read.employee.dependent.attachments",
  "create.employee.dependent.attachments",
  "delete.employee.dependent.attachments",
  "read.employee.rehires",
  "update.employee.base.salary",
  "read.invoices",
  "create.invoices",
  "update.invoices",
  "post.invoices",
  "post.flagged.invoices",
  "cancel.invoices",
  "reverse.invoices",
  "attach.invoice.files",
  "delete.invoice.files",
  "read.invoice.items",
  "create.invoice.items",
  "update.invoice.items",
  "delete.invoice.items",
  "read.employee.health.plans",
  "read.employee.hospital.procedure.plan.limits",
  "read.employee.health.plan.advice",
  "read.users",
  "create.users",
  "update.users",
  "delete.users",
  "enable.users",
  "unlock.users",
  "change.user.passwords",
  "read.user.settings",
  "update.user.settings",
  "read.roles",
  "create.roles",
  "update.roles",
  "delete.roles",
  "read.role.permissions",
  "create.role.permissions",
  "delete.role.permissions",
  "read.user.roles",
  "create.user.roles",
  "delete.user.roles",
  "read.permissions",
  "read.modules",
  "read.tax.rates",
  "create.tax.rates",
  "update.tax.rates",
  "delete.tax.rates",
  "read.reasons",
  "create.reasons",
  "update.reasons",
  "delete.reasons",
  "read.countries",
  "create.countries",
  "update.countries",
  "delete.countries",
  "read.provinces",
  "create.provinces",
  "update.provinces",
  "delete.provinces",
  "read.provider.types",
  "create.provider.types",
  "update.provider.types",
  "delete.provider.types",
  "read.currencies",
  "create.currencies",
  "update.currencies",
  "delete.currencies",
  "read.code.config",
  "create.code.config",
  "update.code.config",
  "delete.code.config",
  "read.leave.reasons",
  "create.leave.reasons",
  "update.leave.reasons",
  "delete.leave.reasons",
  "read.institution.types",
  "create.institution.types",
  "update.institution.types",
  "delete.institution.types",
  "read.service.providers",
  "create.service.providers",
  "update.service.providers",
  "delete.service.providers",
  "read.service.provider.contract.extensions",
  "create.service.provider.contract.extensions",
  "update.service.provider.contract.extensions",
  "read.service.provider.attachments",
  "create.service.provider.attachments",
  "delete.service.provider.attachments",
  "read.hospital.procedure.types",
  "create.hospital.procedure.types",
  "update.hospital.procedure.types",
  "delete.hospital.procedure.types",
  "read.hospital.procedure.groups",
  "create.hospital.procedure.groups",
  "update.hospital.procedure.groups",
  "delete.hospital.procedure.groups",
  "read.hospital.procedure.categories",
  "create.hospital.procedure.categories",
  "update.hospital.procedure.categories",
  "delete.hospital.procedure.categories",
  "read.hospital.procedure.category.types",
  "create.hospital.procedure.category.types",
  "delete.hospital.procedure.category.types",
  "read.hospital.procedure.grouping",
  "create.hospital.procedure.grouping",
  "delete.hospital.procedure.grouping",
  "read.contracts",
  "create.contracts",
  "update.contracts",
  "delete.contracts",
  "read.contract.health.plans",
  "create.contract.health.plans",
  "update.contract.health.plans",
  "delete.contract.health.plans",
  "clone.contract.health.plans",
  "read.contract.departments",
  "create.contract.departments",
  "update.contract.departments",
  "delete.contract.departments",
  "read.contract.department.positions",
  "create.contract.department.positions",
  "update.contract.department.positions",
  "delete.contract.department.positions",
  "read.contract.persons.of.contact",
  "create.contract.persons.of.contact",
  "update.contract.persons.of.contact",
  "delete.contract.persons.of.contact",
  "read.coverage.periods",
  "create.coverage.periods",
  "update.coverage.periods",
  "delete.coverage.periods",
  "start.coverage.periods",
  "close.coverage.periods",
  "read.coverage.period.extensions",
  "create.coverage.period.extensions",
  "update.coverage.period.extensions",
  "read.coverage.period.budgets",
  "create.coverage.period.budgets",
  "update.coverage.period.budgets",
  "delete.coverage.period.budgets",
  "read.coverage.period.budget.transactions",
  "read.organizations",
  "create.organizations",
  "update.organizations",
  "delete.organizations",
  "read.languages",
  "create.languages",
  "update.languages",
  "delete.languages",
  "read.contract.service.providers",
  "create.contract.service.providers",
  "delete.contract.service.providers",
  "read.contract.allowed.hospital.procedures",
  "create.contract.allowed.hospital.procedures",
  "update.contract.allowed.hospital.procedures",
  "delete.contract.allowed.hospital.procedures",
  "read.contract.attachments",
  "create.contract.attachments",
  "delete.contract.attachments",
  "read.reports",
  "read.trend.limits.reports",
  "read.service.provider.reports",
  "read.invoice.reference.reports",
  "read.employee.expenses.reports",
  "read.cost.per.employee.reports",
  "read.contract.hospital.procedures.balances.reports",
  "read.contract.employee.limits.reports",
  "read.dashboards",
  "notify.reports.employee.extract.notification",
  "read.auth.audit.logs",
  "read.system.audit.logs",
] as const;

// Claim principal para entrar na listagem/ficha de colaboradores.
// Escritas no mesmo recurso, como create/update/delete/terminate/rehire.employees,
// continuam a autorizar leitura através da regra READ_IMPLYING_ACTIONS no authStore.
// Claims de dependentes, anexos, salario ou notificacoes nao devem abrir o menu principal.
export const READ_IMPLYING_ACTIONS = [
  "create",
  "update",
  "delete",
  "start",
  "close",
  "execute",
  "unlock",
  "enable",
  "cancel",
  "attach",
  "terminate",
  "change",
  "clone",
  "post",
  "reverse",
  "rehire",
  "notify",
] as const;

export const EMPLOYEE_READ_CLAIMS = [
  CLAIMS.EMPLOYEE.READ,
] as const;

export const EMPLOYEE_DEPENDENTS_READ_CLAIMS = [
  CLAIMS.EMPLOYEE_DEPENDENTS.READ,
  CLAIMS.EMPLOYEE_DEPENDENTS.CREATE,
  CLAIMS.EMPLOYEE_DEPENDENTS.UPDATE,
  CLAIMS.EMPLOYEE_DEPENDENTS.DELETE,
] as const;

export const EMPLOYEE_HEALTH_PLAN_READ_CLAIMS = [
  CLAIMS.EMPLOYEE_HEALTH_PLANS.READ,
  CLAIMS.EMPLOYEE_HOSPITAL_PROCEDURE_PLAN_LIMITS.READ,
  CLAIMS.EMPLOYEE_HEALTH_PLAN_ADVICE.READ,
  CLAIMS.EMPLOYEE.UPDATE,
] as const;

export const EMPLOYEE_SALARY_REVIEW_READ_CLAIMS = [
  CLAIMS.EMPLOYEE.READ,
  CLAIMS.EMPLOYEE_REHIRES.READ,
  CLAIMS.EMPLOYEE.UPDATE_BASE_SALARY,
] as const;

// Acesso de consulta para areas principais da aplicacao.
// A funcao hasPermission tambem entende que create/update/delete implicam read
// quando o recurso e o mesmo, por exemplo "update.contracts" -> "read.contracts".
export const DASHBOARD_READ_CLAIMS = [
  CLAIMS.DASHBOARDS.READ,
] as const;

export const ENTITY_READ_CLAIMS = [
  CLAIMS.ORGANIZATIONS.READ,
  CLAIMS.ORGANIZATIONS.CREATE,
  CLAIMS.ORGANIZATIONS.UPDATE,
  CLAIMS.ORGANIZATIONS.DELETE,
] as const;

export const CONTRACT_READ_CLAIMS = [
  CLAIMS.CONTRACTS.READ,
  CLAIMS.CONTRACTS.CREATE,
  CLAIMS.CONTRACTS.UPDATE,
  CLAIMS.CONTRACTS.DELETE,
] as const;

export const SERVICE_PROVIDER_READ_CLAIMS = [
  CLAIMS.SERVICE_PROVIDERS.READ,
  CLAIMS.SERVICE_PROVIDERS.CREATE,
  CLAIMS.SERVICE_PROVIDERS.UPDATE,
  CLAIMS.SERVICE_PROVIDERS.DELETE,
] as const;

export const INVOICE_READ_CLAIMS = [
  CLAIMS.INVOICES.READ,
  CLAIMS.INVOICES.CREATE,
  CLAIMS.INVOICES.UPDATE,
  CLAIMS.INVOICES.CANCEL,
  CLAIMS.INVOICES.POST,
  CLAIMS.INVOICES.POST_FLAGGED,
  CLAIMS.INVOICES.REVERSE,
  CLAIMS.INVOICE_ITEMS.READ,
  CLAIMS.INVOICE_ITEMS.CREATE,
  CLAIMS.INVOICE_ITEMS.UPDATE,
  CLAIMS.INVOICE_ITEMS.DELETE,
  CLAIMS.INVOICE_FILES.ATTACH,
  CLAIMS.INVOICE_FILES.DELETE,
] as const;

export const REPORT_READ_CLAIMS = [
  CLAIMS.REPORTS.READ,
  CLAIMS.REPORTS.READ_TREND_LIMITS,
  CLAIMS.REPORTS.READ_SERVICE_PROVIDER,
  CLAIMS.REPORTS.READ_INVOICE_REFERENCE,
  CLAIMS.REPORTS.READ_EMPLOYEE_EXPENSES,
  CLAIMS.REPORTS.READ_COST_PER_EMPLOYEE,
  CLAIMS.REPORTS.READ_CONTRACT_HOSPITAL_PROCEDURES_BALANCES,
  CLAIMS.REPORTS.READ_CONTRACT_EMPLOYEE_LIMITS,
] as const;

// Mapa usado para mostrar/proteger cada relatorio da listagem.
// Quando nao existe uma claim ultra-especifica para um relatorio, usamos
// a permissao mais proxima do catalogo recebido do back-end.
export const REPORT_PERMISSION_BY_ID = {
  "100001": CLAIMS.REPORTS.READ_CONTRACT_HOSPITAL_PROCEDURES_BALANCES,
  "100002": CLAIMS.REPORTS.READ_COST_PER_EMPLOYEE,
  "100003": CLAIMS.REPORTS.READ_SERVICE_PROVIDER,
  "100004": CLAIMS.REPORTS.READ_SERVICE_PROVIDER,
  "100005": CLAIMS.REPORTS.READ_SERVICE_PROVIDER,
  "100006": CLAIMS.REPORTS.READ_CONTRACT_EMPLOYEE_LIMITS,
  "100007": CLAIMS.REPORTS.READ,
  "100008": CLAIMS.REPORTS.READ_SERVICE_PROVIDER,
  "100009": CLAIMS.REPORTS.READ_EMPLOYEE_EXPENSES,
  "100010": CLAIMS.REPORTS.READ_INVOICE_REFERENCE,
  "100011": CLAIMS.REPORTS.READ_TREND_LIMITS,
  "100012": CLAIMS.REPORTS.READ_TREND_LIMITS,
  "100013": CLAIMS.REPORTS.READ_TREND_LIMITS,
} as const;

const crudReadClaims = <T extends {
  READ: string;
  CREATE?: string;
  UPDATE?: string;
  DELETE?: string;
}>(claims: T) => [
  claims.READ,
  claims.CREATE,
  claims.UPDATE,
  claims.DELETE,
].filter(Boolean) as string[];

export const SETTINGS_READ_CLAIMS = [
  ...crudReadClaims(CLAIMS.CODE_CONFIG),
  ...crudReadClaims(CLAIMS.SCHEDULED_JOBS),
  ...crudReadClaims(CLAIMS.SCHEDULED_PARAMETERS),
] as const;

export const ACCESS_MANAGEMENT_READ_CLAIMS = [
  ...crudReadClaims(CLAIMS.USERS),
  CLAIMS.USERS.ENABLE,
  CLAIMS.USERS.UNLOCK,
  CLAIMS.USERS.CHANGE_PASSWORDS,
  CLAIMS.USERS.READ_SETTINGS,
  CLAIMS.USERS.UPDATE_SETTINGS,
  ...crudReadClaims(CLAIMS.ROLES),
  ...crudReadClaims(CLAIMS.ROLE_PERMISSIONS),
  ...crudReadClaims(CLAIMS.USER_ROLES),
  CLAIMS.PERMISSIONS.READ,
  CLAIMS.MODULES.READ,
] as const;

export const BASE_TABLE_READ_CLAIMS = [
  ...crudReadClaims(CLAIMS.COUNTRIES),
  ...crudReadClaims(CLAIMS.PROVINCES),
  ...crudReadClaims(CLAIMS.CURRENCIES),
  ...crudReadClaims(CLAIMS.LANGUAGES),
  ...crudReadClaims(CLAIMS.INSTITUTION_TYPES),
  ...crudReadClaims(CLAIMS.LEAVE_REASONS),
  ...crudReadClaims(CLAIMS.REASONS),
  ...crudReadClaims(CLAIMS.PROVIDER_TYPES),
  ...crudReadClaims(CLAIMS.TAX_RATES),
  ...crudReadClaims(CLAIMS.HOSPITAL_PROCEDURE_TYPES),
  ...crudReadClaims(CLAIMS.HOSPITAL_PROCEDURE_CATEGORIES),
  ...crudReadClaims(CLAIMS.HOSPITAL_PROCEDURE_CATEGORY_TYPES),
  ...crudReadClaims(CLAIMS.HOSPITAL_PROCEDURE_GROUPS),
  ...crudReadClaims(CLAIMS.HOSPITAL_PROCEDURE_GROUPING),
] as const;

const crudPermissions = <T extends {
  READ: string;
  CREATE?: string;
  UPDATE?: string;
  DELETE?: string;
}>(claims: T) => ({
  ACCESS: crudReadClaims(claims),
  LIST: crudReadClaims(claims),
  VIEW: claims.READ,
  CREATE: claims.CREATE,
  UPDATE: claims.UPDATE,
  DELETE: claims.DELETE,
});

// Alias usado pela camada de UI já implementada.
export const PERMISSIONS = {
  ...CLAIMS,
  DASHBOARD: {
    ACCESS: DASHBOARD_READ_CLAIMS,
    VIEW: CLAIMS.DASHBOARDS.READ,
  },
  ENTITIES: {
    ...CLAIMS.ORGANIZATIONS,
    ACCESS: ENTITY_READ_CLAIMS,
    LIST: ENTITY_READ_CLAIMS,
    VIEW: CLAIMS.ORGANIZATIONS.READ,
    CREATE: CLAIMS.ORGANIZATIONS.CREATE,
    UPDATE: CLAIMS.ORGANIZATIONS.UPDATE,
    DELETE: CLAIMS.ORGANIZATIONS.DELETE,
  },
  CONTRACTS: {
    ...CLAIMS.CONTRACTS,
    ACCESS: CONTRACT_READ_CLAIMS,
    LIST: CONTRACT_READ_CLAIMS,
    VIEW: CLAIMS.CONTRACTS.READ,
    CREATE: CLAIMS.CONTRACTS.CREATE,
    UPDATE: CLAIMS.CONTRACTS.UPDATE,
    DELETE: CLAIMS.CONTRACTS.DELETE,
    DEPARTMENTS_VIEW: CLAIMS.CONTRACT_DEPARTMENTS.READ,
    DEPARTMENT_POSITIONS_VIEW: CLAIMS.CONTRACT_DEPARTMENT_POSITIONS.READ,
    DEPARTMENTS_MANAGE: CLAIMS.CONTRACT_DEPARTMENTS.UPDATE,
    HEALTH_PLANS_VIEW: CLAIMS.CONTRACT_HEALTH_PLANS.READ,
    HEALTH_PLANS_MANAGE: CLAIMS.CONTRACT_HEALTH_PLANS.UPDATE,
    COVERAGE_PERIODS_VIEW: CLAIMS.COVERAGE_PERIODS.READ,
    COVERAGE_PERIODS_MANAGE: CLAIMS.COVERAGE_PERIODS.UPDATE,
    CONTACTS_VIEW: CLAIMS.CONTRACT_PERSONS_OF_CONTACT.READ,
    SERVICE_PROVIDERS_VIEW: CLAIMS.CONTRACT_SERVICE_PROVIDERS.READ,
    EMPLOYEES_VIEW: EMPLOYEE_READ_CLAIMS,
  },
  SERVICE_PROVIDERS: {
    ...CLAIMS.SERVICE_PROVIDERS,
    ACCESS: SERVICE_PROVIDER_READ_CLAIMS,
    LIST: SERVICE_PROVIDER_READ_CLAIMS,
    VIEW: CLAIMS.SERVICE_PROVIDERS.READ,
    CREATE: CLAIMS.SERVICE_PROVIDERS.CREATE,
    UPDATE: CLAIMS.SERVICE_PROVIDERS.UPDATE,
    DELETE: CLAIMS.SERVICE_PROVIDERS.DELETE,
  },
  INVOICES: {
    ...CLAIMS.INVOICES,
    ACCESS: INVOICE_READ_CLAIMS,
    LIST: INVOICE_READ_CLAIMS,
    VIEW: CLAIMS.INVOICES.READ,
    CREATE: CLAIMS.INVOICES.CREATE,
    UPDATE: CLAIMS.INVOICES.UPDATE,
    CANCEL: CLAIMS.INVOICES.CANCEL,
    POST: CLAIMS.INVOICES.POST,
    POST_FLAGGED: CLAIMS.INVOICES.POST_FLAGGED,
    REVERSE: CLAIMS.INVOICES.REVERSE,
  },
  REPORTS: {
    ...CLAIMS.REPORTS,
    ACCESS: REPORT_READ_CLAIMS,
    LIST: REPORT_READ_CLAIMS,
    VIEW: CLAIMS.REPORTS.READ,
    GENERATE: CLAIMS.REPORTS.READ,
    BY_ID: REPORT_PERMISSION_BY_ID,
  },
  USER_PROFILE: {
    ACCESS: [
      CLAIMS.USERS.READ_SETTINGS,
      CLAIMS.USERS.UPDATE_SETTINGS,
    ],
    VIEW: CLAIMS.USERS.READ_SETTINGS,
    UPDATE: CLAIMS.USERS.UPDATE_SETTINGS,
  },
  SETTINGS: {
    ACCESS: SETTINGS_READ_CLAIMS,
    ALERTS: {
      ACCESS: [
        ...crudReadClaims(CLAIMS.SCHEDULED_JOBS),
        ...crudReadClaims(CLAIMS.SCHEDULED_PARAMETERS),
      ],
      JOBS: crudPermissions(CLAIMS.SCHEDULED_JOBS),
      PARAMETERS: crudPermissions(CLAIMS.SCHEDULED_PARAMETERS),
    },
    CODE_CONFIG: crudPermissions(CLAIMS.CODE_CONFIG),
  },
  ACCESS_MANAGEMENT: {
    ACCESS: ACCESS_MANAGEMENT_READ_CLAIMS,
    USERS: {
      ...crudPermissions(CLAIMS.USERS),
      ACCESS: [
        ...crudReadClaims(CLAIMS.USERS),
        CLAIMS.USERS.ENABLE,
        CLAIMS.USERS.UNLOCK,
        CLAIMS.USERS.CHANGE_PASSWORDS,
        CLAIMS.USER_ROLES.READ,
        CLAIMS.USER_ROLES.CREATE,
        CLAIMS.USER_ROLES.DELETE,
      ],
      LIST: [
        ...crudReadClaims(CLAIMS.USERS),
        CLAIMS.USERS.ENABLE,
        CLAIMS.USERS.UNLOCK,
        CLAIMS.USERS.CHANGE_PASSWORDS,
        CLAIMS.USER_ROLES.READ,
        CLAIMS.USER_ROLES.CREATE,
        CLAIMS.USER_ROLES.DELETE,
      ],
      ENABLE: CLAIMS.USERS.ENABLE,
      UNLOCK: CLAIMS.USERS.UNLOCK,
      CHANGE_PASSWORDS: CLAIMS.USERS.CHANGE_PASSWORDS,
      MANAGE_ROLES: CLAIMS.USER_ROLES.CREATE,
    },
    ROLES: {
      ...crudPermissions(CLAIMS.ROLES),
      ACCESS: [
        ...crudReadClaims(CLAIMS.ROLES),
        CLAIMS.ROLE_PERMISSIONS.READ,
        CLAIMS.ROLE_PERMISSIONS.CREATE,
        CLAIMS.ROLE_PERMISSIONS.DELETE,
      ],
      LIST: [
        ...crudReadClaims(CLAIMS.ROLES),
        CLAIMS.ROLE_PERMISSIONS.READ,
        CLAIMS.ROLE_PERMISSIONS.CREATE,
        CLAIMS.ROLE_PERMISSIONS.DELETE,
      ],
      MANAGE_PERMISSIONS: CLAIMS.ROLE_PERMISSIONS.CREATE,
    },
    USER_ROLES: crudPermissions(CLAIMS.USER_ROLES),
    ROLE_PERMISSIONS: crudPermissions(CLAIMS.ROLE_PERMISSIONS),
    MODULES: {
      ACCESS: CLAIMS.MODULES.READ,
      LIST: CLAIMS.MODULES.READ,
      VIEW: CLAIMS.MODULES.READ,
    },
    PERMISSIONS: {
      ACCESS: CLAIMS.PERMISSIONS.READ,
      LIST: CLAIMS.PERMISSIONS.READ,
      VIEW: CLAIMS.PERMISSIONS.READ,
    },
  },
  BASE_TABLES: {
    ACCESS: BASE_TABLE_READ_CLAIMS,
    COUNTRIES: crudPermissions(CLAIMS.COUNTRIES),
    PROVINCES: crudPermissions(CLAIMS.PROVINCES),
    CURRENCIES: crudPermissions(CLAIMS.CURRENCIES),
    LANGUAGES: crudPermissions(CLAIMS.LANGUAGES),
    INSTITUTION_TYPES: crudPermissions(CLAIMS.INSTITUTION_TYPES),
    LEAVE_REASONS: crudPermissions(CLAIMS.LEAVE_REASONS),
    REASONS: crudPermissions(CLAIMS.REASONS),
    PROVIDER_TYPES: crudPermissions(CLAIMS.PROVIDER_TYPES),
    TAX_RATES: crudPermissions(CLAIMS.TAX_RATES),
    HOSPITAL_PROCEDURE_TYPES: crudPermissions(CLAIMS.HOSPITAL_PROCEDURE_TYPES),
    HOSPITAL_PROCEDURE_CATEGORIES: crudPermissions(CLAIMS.HOSPITAL_PROCEDURE_CATEGORIES),
    HOSPITAL_PROCEDURE_CATEGORY_TYPES: crudPermissions(CLAIMS.HOSPITAL_PROCEDURE_CATEGORY_TYPES),
    HOSPITAL_PROCEDURE_GROUPS: crudPermissions(CLAIMS.HOSPITAL_PROCEDURE_GROUPS),
    HOSPITAL_PROCEDURE_GROUPING: crudPermissions(CLAIMS.HOSPITAL_PROCEDURE_GROUPING),
  },
  EMPLOYEE: {
    ...CLAIMS.EMPLOYEE,
    ACCESS: EMPLOYEE_READ_CLAIMS,
    LIST: EMPLOYEE_READ_CLAIMS,
    VIEW: EMPLOYEE_READ_CLAIMS,
    CREATE: CLAIMS.EMPLOYEE.CREATE,
    UPDATE: CLAIMS.EMPLOYEE.UPDATE,
    DELETE: CLAIMS.EMPLOYEE.DELETE,
    TERMINATE_CONTRACT: CLAIMS.EMPLOYEE.TERMINATE,
    REHIRE_CONTRACT: CLAIMS.EMPLOYEE.REHIRE,
    SEND_EXTRACT_NOTIFICATION: CLAIMS.REPORTS.NOTIFY_EMPLOYEE_EXTRACT,
    SALARY_REVIEW_VIEW: EMPLOYEE_SALARY_REVIEW_READ_CLAIMS,
    SALARY_REVIEW_UPDATE: CLAIMS.EMPLOYEE.UPDATE_BASE_SALARY,
    DEPENDENTS_VIEW: EMPLOYEE_DEPENDENTS_READ_CLAIMS,
    DEPENDENTS_MANAGE: CLAIMS.EMPLOYEE_DEPENDENTS.UPDATE,
    DEPENDENTS_CREATE: CLAIMS.EMPLOYEE_DEPENDENTS.CREATE,
    DEPENDENTS_DELETE: CLAIMS.EMPLOYEE_DEPENDENTS.DELETE,
    HEALTH_PLAN_VIEW: EMPLOYEE_HEALTH_PLAN_READ_CLAIMS,
    HEALTH_PLAN_MANAGE: CLAIMS.EMPLOYEE.UPDATE,
    FORM_IDENTIFICATION_VIEW: EMPLOYEE_READ_CLAIMS,
    FORM_IDENTIFICATION_UPDATE: CLAIMS.EMPLOYEE.UPDATE,
    FORM_CONTACT_VIEW: EMPLOYEE_READ_CLAIMS,
    FORM_CONTACT_UPDATE: CLAIMS.EMPLOYEE.UPDATE,
    FORM_INSTITUTION_VIEW: EMPLOYEE_READ_CLAIMS,
    FORM_INSTITUTION_UPDATE: CLAIMS.EMPLOYEE.UPDATE,
  },
} as const;

export type Permission = string;
export type PermissionRequirement = Permission | readonly PermissionRequirement[];
